version: '3'
name: tic-tac-toe

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    environment:
      - IP=${VITE_APP_IP}

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 5173:80
    environment:
      - IP=${VITE_APP_IP}
    depends_on:
      - server
